name: Update README with Stats and Graphs

on:
  schedule:
    - cron: '0 3 * * *' # 每天 UTC 时间 3 点更新
  workflow_dispatch: # 手动触发

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 安装 Python 依赖
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install requests

      # 运行脚本更新 README.md
      - name: Update README Content
        run: |
          python3 update_readme.py

      # 提交更新到仓库
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add README.md
          git commit -m "Auto-update README with latest stats and graphs"
          git push
